name = "WildLight"
author = "Alfakynz"
version = "4.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6072f5068e3965cddc2404ef8c1aaf87451c37fa3d471a0665857311ce26674"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
