name = "WildLight"
author = "Alfakynz"
version = "4.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "396789e96f7f07d72fa1020b2b183197802d3b59b6f9fad4c1758120282965dd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
