name = "WildLight"
author = "Alfakynz"
version = "4.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fd2bdccf810c4fff3163496108e1545eef43d92a2550e2bbd45b2f8f34fe6f6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
