name = "WildLight"
author = "Alfakynz"
version = "4.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d497308f4016744809f9276ab05d31523b6ba7258b0483f435b3570f4c3039d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
